Ветка else в конструкции try…except…else будет выполнена только в том случае, если исключения не было возбуждено в блоке
try. Если в блоке try произошло исключение, то выполнение программы переходит к соответствующему блоку except, и ветка
else пропускается. Если блок except не указан, то исключение будет возбуждено дальше, а программа завершится с
сообщением об ошибке.

Пример, в котором будет выполнена ветка else:

```python
try:
# какой-то код здесь
except:
# код для обработки исключения
else:
# код для выполнения, если исключения нет
```

Если в блоке try не возникает исключений, то выполняется код в блоке else.

<div align="right">

[Вернуться к вопросам](../Вопросы.md)

</div>
